server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/inflearn2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #?? ??? ???, ?? ???? ? ???, ??? ???? ?? ???? ????
    show-sql: true #?? ??? ????? 'show-sql: true'? ? ?? 'format_sql'? ??? ??? ???...
    defer-datasource-initialization: true #?? DB? ?? ????? ????, ?? ?? ???? ?? ???? ???? ??? ?????? ?? ?
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true


  messages:
    basename: messages #??? ??? ??? ??(??? ??)? ??? 'messages'?? ???? ?
    #'??? ??'-->'messages.properties'? ?????. ??? 'messages'? ?? ?? 'yml ??'?? ???
    #'basename: messages'? 'messages'? ???? ??? ?!


  devtools:
    livereload:
      enabled: true


logging:
  level:
    org:
      springframework: DEBUG
    hibernate: DEBUG
    

# ??? ??? JPA ???? ??
#logging.level:
# org.hibernate.SQL: debug
# org.hibernate.type: trace #??? ?? 2.x, hibernate5.
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
